# 사이킷런
- 지도학습: 학습을 위한 다양한 fearture와 label 데이터로 모델을 학습한 뒤 별도의 
table set에서 미지의 label 측정
- 비지도 학습: 차원축소, 클러스터링, Feature Extraction
- "분류","회귀"<- 지도학습의 방법
- ->이때 분류 알고리즘으로 구현한 클래스: Classifier + 회귀 알고리즘으로 구현한 클래스: Regressor =  Estimator: fit(),predict()을 내부에서 구현하고 있음
### 예제 데이터 
- sklearn.datasets: 사이킷런 자체적으로 제공하는 데이터 세트 생성
### Feature 처리
- sklearn.processing: 데이터 전처리에 필요한 가공 기능 제공
- sklearn.feature_selection: 알고리즘에 영향 끼치는 featue 우선순위로 select
+ text,image data를 벡터화해서 feature extract
### 차원 축소
- sklearn.decompositon: 차원 축소 기능
### 데이터 분리
- sklearn.model_selction: 학습용/테스트용 데이터 분리, 최적 parameter 추출
### 평가
- sklearn.metrics: 평가, 다양한 성능 측정 방법 제공
### ML 알고리즘
- sklearn.ensemble: 앙상블 제공 알고리즘
- sklearn.linear_model:회귀 관련 알고리즘 제공
- sklearn.naive_bayes: 나이브 베이즈 알고리즘 제공
- sklearn.neighbors: 최근접 이웃 알고리즘 제공
- sklearn.svm: 서포트 벡터 머신 알고리즘 제공
- sklearn.tree: 의사 결정 트리 알고리즘 제공
- sklearn.cluster: 비지도 클러스터링 알고리즘 제공
### 유틸리티
- sklearn.pipeline: 위의 것들 함께 묶어서 실행할 수 있는 유틸리티 제공
- 하이퍼파라미터: 머신러닝 알고리즘 별로 최적의 학습을 위해 직접 입력하는 파라미터
- 의사결정트리 알고리즘

## 분류
1. 데이터 세트 분리: 학습용, 테스트용 데이터로 분리
2. 모델학습: 학습용 데이터로 ML 알고리즘 적용
3. 예측 수행: 학습된 ML 모델로 테스트용 데이터 예측
4. 평가:예측된 결과값과 테스트용 데이터 실제 결과값 비교 

### 예제데이터
- datasets.makeclassification(): 분류 위한 데이터 무작위 생성
- datasets.make_blobs(): 클러스터링 위한 

In [ ]:
conda install scikit-learn

In [71]:
import sklearn
print(sklearn.__version__)

1.0.2


In [24]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [17]:
import pandas as pd
iris=load_iris()
iris_data=iris.data
iris_label=iris.target
print("iris target값:",iris_label)
print("iris target명:",iris.target_names)
iris_df=pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [ ]:
## 이때 row 0,1,2가 label/target의미
학습용/테스트용 데이터 분리해야

In [30]:
X_train,X_test,y_train,y_test=train_test_split(iris_data,iris_label,test_size=0.2,random_state=11)

X_train<-학습용 feature 데이터 세트
X_test<-테스트용 fearture 데이터 세트
y_train<-학습용 label 데이터 세트
y_test<-테스트용 label 데이터 세트
test_size=0.2<- 전체데이터 중 test=20%, train=80%
random_state<-수행할 때마다 동일한 데이터 세트 분리하기 위해

In [35]:
#DecisionTreeClassifier 객체 생성 
dt_clf=DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train,y_train)
#학습이 완료됨

DecisionTreeClassifier(random_state=11)

In [37]:
#학습이 완료된 후 예측 수행
pred=dt_clf.predict(X_test)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [40]:
#예측 결과 기반으로 예측 성능 평가
from sklearn.metrics import accuracy_score
print("예측 정확도:{0:.4f}".format(accuracy_score(y_test,pred)))

예측 정확도:0.9333


In [41]:
from sklearn.datasets import load_iris
iris_data=load_iris()
print(type(iris_data))

<class 'sklearn.utils.Bunch'>


In [43]:
keys=iris_data.keys()
print("붓꽃 데이터 세트의 키들:",keys)
#data: feature의 데이터 세트
#target: 분류 시 label값, 회귀 시 숫자 결과값 데이터 세트
#target_names:label 이름
#DESCR 데이터 세트에 대한 feature 설명
#데이터 세트: 딕셔너리 형태

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [46]:
print("\n  feature_names 의 type",type(iris_data.feature_names))
print("\n  feature_names 의 length",len(iris_data.feature_names))
print(iris_data.feature_names)
print("\n  target_names 의 type",type(iris_data.target_names))
print("\n  target_names 의 length",len(iris_data.target_names))
print(iris_data.target_names)
print("\n  data 의 type",type(iris_data.data))
print("\n  data 의 shape",iris_data.data.shape)
print(iris_data['data'])
print("\n  target 의 type",type(iris_data.target))
print("\n  target 의 shape",iris_data.target.shape)
print(iris_data.target)
print(iris_data.frame)


  feature_names 의 type <class 'list'>

  feature_names 의 length 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

  target_names 의 type <class 'numpy.ndarray'>

  target_names 의 length 3
['setosa' 'versicolor' 'virginica']

  data 의 type <class 'numpy.ndarray'>

  data 의 shape (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1

## Model Selection 모듈


### 학습용/테스트용 데이터 세트 분리 

In [48]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
iris=load_iris()
dt_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target
dt_clf.fit(train_data,train_label)

pred=dt_clf.predict(train_data)
print("예측 정확도:",accuracy_score(train_label,pred))

## 이미 학습한 학습용 데이터 세트를 기반을 예측했기 때문에 정확도 100%가 나옴
## -> 테스트용 데이터를 따로 분리해야함

예측 정확도: 1.0


In [51]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
df_clf=DecisionTreeClassifier()
iris_data=load_iris()
X_train,X_test,y_train,y_test=train_test_split(iris_data.data,iris_data.target,test_size=0.3,random_state=121)

In [52]:
dt_clf.fit(X_train,y_train)
pred=dt_clf.predict(X_test)
print("예측 정확도:{0:.4f}".format(accuracy_score(y_test,pred)))

예측 정확도:0.9556


## 교차 검증

- 학습용 데이터에만 과도하게 최적화된 overfitting 문제 생길 수도
- > 별도의 여러 세트로 구성된 학습용 데이터 세트와 테스트용 데이터 세트에서 학습과 평가를 수행하는 것

### K폴드 교차 검증
- k개의 데이터 폴드 세트를 만들어서 k번만큼 각 폴드 세트에 학습과 테스트 평가를 반복적으로 수행하는 것-> 학습용 데이터& 테스트용 데이터 계속 바뀜


In [57]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np
iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

#5개의 폴드 세트로 분리하는 KFold 객체와 
#폴드 세트별 정확도를 담을 리스트 객체 생성
kfold=KFold(n_splits=5)
cv_accuracy=[]
print('불꽃 데이터 세트 크기:',features.shape)

불꽃 데이터 세트 크기: (150, 4)


In [59]:
n_iter=0
#KFold 객체의 split()를 호출하면 폴드 별 학습용, 테스트용 row index를 array로 반환
for train_index,test_index in kfold.split(features):
    #kfold.split()으로 반환된 index를 이용해 학습용, 테스트용 데이터 추출
    X_train,X_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    #학습 & 예측
    dt_clf.fit(X_train,y_train)
    pred=dt_clf.predict(X_test)
    n_iter+=1
    #반복 시마다 정확도 측정
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    print('\n{0} 교차 검증 정확도:{1}, 학습용 데이터 크기:{2}, 테스트용 데이터의 크기:{3}'.format(n_iter,accuracy,train_size,test_size))
    print("#{0} 테스트용 set index:{1}".format(n_iter,test_index))
    cv_accuracy.append(accuracy)
    
#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n##평균 검증 정확도:',np.mean(cv_accuracy))


1 교차 검증 정확도:1.0, 학습용 데이터 크기:120, 테스트용 데이터의 크기:30
#1 테스트용 set index:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

2 교차 검증 정확도:0.9667, 학습용 데이터 크기:120, 테스트용 데이터의 크기:30
#2 테스트용 set index:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

3 교차 검증 정확도:0.8667, 학습용 데이터 크기:120, 테스트용 데이터의 크기:30
#3 테스트용 set index:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

4 교차 검증 정확도:0.9333, 학습용 데이터 크기:120, 테스트용 데이터의 크기:30
#4 테스트용 set index:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

5 교차 검증 정확도:0.7333, 학습용 데이터 크기:120, 테스트용 데이터의 크기:30
#5 테스트용 set index:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

##평균 검증 정확도: 0.9


### Stratified K폴드
> 불균형한 분포도를 가진 label 데이터 집합을 위한 K Fold 방식 
>> 원본 데이터의 label 분포를 먼저 고려한 후 이 분포와 동일하게 학습용, 테스트용 세트를 분배함

In [62]:
import pandas as pd
iris=load_iris()
iris_df=pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()
## 각 label값이 모두 50개로 동일함

0    50
1    50
2    50
Name: label, dtype: int64

In [64]:
kfold=KFold(n_splits=3)
n_iter=0
for train_index,test_index in kfold.split(iris_df):
    n_iter+=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print("\n ##교차 검증:{0}".format(n_iter))
    print('학습용 label 데이터 분포:\n',label_train.value_counts())
    print('테스트용 label 데이터 분포:\n',label_test.value_counts())


 ##교차 검증:1
학습용 label 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
테스트용 label 데이터 분포:
 0    50
Name: label, dtype: int64

 ##교차 검증:2
학습용 label 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
테스트용 label 데이터 분포:
 1    50
Name: label, dtype: int64

 ##교차 검증:3
학습용 label 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
테스트용 label 데이터 분포:
 2    50
Name: label, dtype: int64


In [66]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=3)
n_iter=0
for train_index,test_index in skf.split(iris_df,iris_df['label']):
    n_iter+=1 
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print("\n ##교차 검증:{0}".format(n_iter))
    print('학습용 label 데이터 분포:\n',label_train.value_counts())
    print('테스트용 label 데이터 분포:\n',label_test.value_counts())


 ##교차 검증:1
학습용 label 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
테스트용 label 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64

 ##교차 검증:2
학습용 label 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
테스트용 label 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64

 ##교차 검증:3
학습용 label 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
테스트용 label 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [72]:
dt_clf=DecisionTreeClassifier(random_state=156)
skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

#StratifiedKFold 의 split()호출 시 반드시 label 데이터 세트도 추가 입력 필요
for train_index,test_index in skfold.split(features,label):
    #split()으로 반환된 index를 이용해 학습용, 테스트용 데이터 추출
    X_train,X_test=features[train_index],features[test_index]
    y_train,y_test=label[train_index],label[test_index]
    #학습 & 예측
    dt_clf.fit(X_train,y_train)
    pred=dt_clf.predict(X_test)
    #반복 시마다 정확도 측정
    n_iter+=1
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    print('\n{0}교차 검증 정확도:{1},학습용 데이터 크기:{2},테스트용 데이터 크기:{3}'.format(n_iter,accuracy,train_size,test_size))
    print("#{0} 테스트용 세트 index:\n{1}".format(n_iter,test_index))
    cv_accuracy.append(accuracy)
    #교차 검증별 정확도 및 평균 정확도 계산
    print("\n ## 교차 검증별 정확도:",np.round(cv_accuracy,4))
    print("## 평균 정확도:",np.mean(cv_accuracy))


1교차 검증 정확도:0.98,학습용 데이터 크기:100,테스트용 데이터 크기:50
#1 테스트용 세트 index:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

 ## 교차 검증별 정확도: [0.98]
## 평균 정확도: 0.98

2교차 검증 정확도:0.94,학습용 데이터 크기:100,테스트용 데이터 크기:50
#2 테스트용 세트 index:
[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

 ## 교차 검증별 정확도: [0.98 0.94]
## 평균 정확도: 0.96

3교차 검증 정확도:0.98,학습용 데이터 크기:100,테스트용 데이터 크기:50
#3 테스트용 세트 index:
[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

 ## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 정확도: 0.9666666666666667


In [73]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score,cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)
data=iris_data.data
label=iris_data.target
scores=cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('교차 검증별 정확도:',np.round(scores,4))
print('평균 검증별 정활도:',np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증별 정활도: 0.9667


### GridSearchCV: 최적의 파라미터 튜닝
> Grid 방식으로 촘촘하게 파라미터 입력하면서 테스트

In [76]:
grid_parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}

In [78]:
grid_parameters

{'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]}

In [79]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
iris=load_iris()
X_train,X_test,y_train,y_test=train_test_split(iris_data.data,iris_data.target,test_size=0.2,random_state=121)
dtree=DecisionTreeClassifier()
parameters=grid_parameters

In [82]:
import pandas as pd
#param_grid 의 하이퍼 파라미터를 3개의 train,test set fold로 나누어 테스트 수행
#refit=True가 디폴트: 가장 좋은 파라미터 설정으로 재학습 시킴
grid_dtree=GridSearchCV(dtree,param_grid=parameters,cv=3,refit=True)
grid_dtree.fit(X_train,y_train)
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [88]:
print('GridSearchCV 최적 파라미터:',grid_dtree.best_params_)
print('GridSeachCV 최고 정확도:{0:.4}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSeachCV 최고 정확도:0.975


In [92]:
#GridSearchCV의 refit으로 이미 학습된 estimator 변환
estimator=grid_dtree.best_estimator_
pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도:{0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도:0.9667
