# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [70]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MYCOM/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/MYCOM/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MYCOM/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/MYCOM/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MYCOM/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/MYCOM/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/MYCOM/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/MYCOM/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

#### 3. Create a null vector of size 10 (★☆☆)

In [2]:
array1=np.zeros((10,))
print(array1)
print(array1.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)


#### 4. How to find the memory size of any array (★☆☆)

In [71]:
Z=np.zeros(10)
print("length : %d / itemsize : %d / memorysize : %d bytes" % (Z.size  , Z.itemsize ,Z.size*Z.itemsize))

length : 10 / itemsize : 8 / memorysize : 80 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [72]:
array1=np.zeros((10,))
array1[4]=1
print(array1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
array2=np.arange(start=10,stop=50)
print(array2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
array3=np.arange(10)
sortarray3=np.sort(array3)[::-1]
print(sortarray3)

[9 8 7 6 5 4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
array=np.arange(9)
array2d=array.reshape(3,3)
print(array2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [61]:
array1d=np.array([1,2,0,0,4,0])
array2=array1d[array1d!=0]
print(array2)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [74]:
array1=np.identity(3)
print(array1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [79]:
array1=np.random.random((3,3,3))
print(array1)

[[[0.45963825 0.92244026 0.48489196]
  [0.83542839 0.12069582 0.56252548]
  [0.4073132  0.67205979 0.19682339]]

 [[0.5092609  0.81574584 0.50589151]
  [0.86811884 0.10618083 0.43997123]
  [0.14906122 0.89686138 0.53000275]]

 [[0.26154554 0.62112258 0.62391776]
  [0.72742024 0.78292947 0.90925418]
  [0.39345548 0.1053197  0.28438668]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [64]:
array1=np.zeros((10,10))
for i in range(10):
    for j in range(10):
        array1[i][j]=np.random.random()*10


print(np.min(array1))
print(np.max(array1))

0.12410955679449609
9.930689424264505


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [87]:
array1=np.random.random((30,))

print(array1)
mean=np.mean(array1)
print('mean:',mean)

[0.72939585 0.75752885 0.4093407  0.88767222 0.99406938 0.90948584
 0.8043251  0.58724695 0.48687518 0.62571798 0.21879892 0.29419328
 0.84898058 0.55292965 0.12124909 0.47836531 0.76998798 0.59719503
 0.72753141 0.77995129 0.1158687  0.82252688 0.67925277 0.43436512
 0.65979421 0.58605083 0.07758612 0.72755059 0.01343979 0.72686888]
mean: 0.5808048157475233


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [82]:
array1=np.ones((10,10))
array1[1:-1,1:-1] = 0
print(array1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [132]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [96]:
array1=np.zeros((5,5))
for i in range(5):
    for j in range(5):
        if (i-j)==1:
            array1[i][j]=i
print(array1)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [98]:
array1=np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i+j)%2==0:
            array1[i][j]=2
print(array1)

[[2. 0. 2. 0. 2. 0. 2. 0.]
 [0. 2. 0. 2. 0. 2. 0. 2.]
 [2. 0. 2. 0. 2. 0. 2. 0.]
 [0. 2. 0. 2. 0. 2. 0. 2.]
 [2. 0. 2. 0. 2. 0. 2. 0.]
 [0. 2. 0. 2. 0. 2. 0. 2.]
 [2. 0. 2. 0. 2. 0. 2. 0.]
 [0. 2. 0. 2. 0. 2. 0. 2.]]


In [133]:
array17 = np.zeros((8, 8))
array17[1::2, ::2] = 1
array17[::2, 1::2] = 1
print (array17)
##또다른방법

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [105]:
array18=np.unravel_index(100, (6,7,8))
print(array18)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [110]:
array19=np.random.random((5,5))*20
print(array19)
mean = np.mean(array19)
sd = np.sqrt(array19)
print('\n')
print((array19 - mean) / sd)

[[ 5.71354603 12.17671279 11.36346149 15.70395138  0.54912033]
 [13.98743477  0.65871308  4.19544238  4.16556507  1.20611567]
 [11.41342411 14.04955584  0.30865065  6.73700364  2.08406989]
 [10.26264133 13.61314189 19.84057952  0.88368141  1.63933505]
 [12.30090547 13.41142567 13.52895025  5.23117717 11.22027103]]


[[ -1.06105776   1.12534782   0.92366985   1.88102266 -10.39190142]
 [  1.53413733  -9.35309908  -1.97939579  -2.00112043  -6.41364766]
 [  0.93643488   1.54731518 -14.29385905  -0.58283504  -4.27098475]
 [  0.62832022   1.45363944   2.60216993  -7.8359301   -5.1629488 ]
 [  1.15506265   1.40944927   1.43526595  -1.31980091   0.88679732]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [115]:
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [56]:
array1=np.arange(15)
array1=array1.reshape(5,3)
array2=np.arange(6)
array2=array2.reshape(3,2)
print(np.dot(array1,array2))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [117]:
array22=np.arange(10)
array22[(3 < array22) & (array22 <8)] *= -1
print(array22)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [118]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [130]:
Z = np.arange(4)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[ 1  1  4 27]
[0 1 2 4]
[False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j]
[0. 1. 2. 3.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [2]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\MYCOM\AppData\Local\Temp\ipykernel_20572\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\MYCOM\AppData\Local\Temp\ipykernel_20572\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [92]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)
emptyList=[]
for i in range(10):
    if i in Z1 and i in Z2:
        emptyList.append(i)
print(emptyList)
print(1 in Z1)

[6 6 7 2 7 3 4 1 7 9]
[9 8 8 9 8 9 5 5 7 1]
[1, 7, 9]
True


In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [12]:
np.sqrt(-1)

C:\Users\MYCOM\AppData\Local\Temp\ipykernel_20572\3438155168.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

In [13]:
np.emath.sqrt(-1)

1j

In [14]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [17]:
Z = np.arange('2016-06-01', '2016-06-30', dtype='datetime64[D]')
print(Z)

['2016-06-01' '2016-06-02' '2016-06-03' '2016-06-04' '2016-06-05'
 '2016-06-06' '2016-06-07' '2016-06-08' '2016-06-09' '2016-06-10'
 '2016-06-11' '2016-06-12' '2016-06-13' '2016-06-14' '2016-06-15'
 '2016-06-16' '2016-06-17' '2016-06-18' '2016-06-19' '2016-06-20'
 '2016-06-21' '2016-06-22' '2016-06-23' '2016-06-24' '2016-06-25'
 '2016-06-26' '2016-06-27' '2016-06-28' '2016-06-29']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [91]:
def fun26(A,B):

    result=np.multiply(np.add(A,B),np.divide(np.negative(A),2),out=None)
    return result

fun26([3.2],[5,6])

array([-13.12, -14.72])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [16]:
def func30(a):
    result=[]
    for i in range(len(a)):
        if a[i]>0:
            result.append(a[i]//1)
    return result

aa=np.array([-3.4,5.6,7.8,9])
print(func30(aa))

[5.0, 7.0, 9.0]


In [17]:
def func30(a):
    result=[]
    for i in range(len(a)):
        if a[i]>0:
            result.append(a[i]-a[i]%1)
    return result

aa=np.array([-3.4,5.6,7.8,9])
print(func30(aa))

[5.0, 7.0, 9.0]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [25]:
np31=np.zeros((5,5))
for i in range(1,5):
    np31[:,i]=i
print(np31)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [26]:
np31_2=np.zeros((5,5))
np31_2+=np.arange(5)
print(np31_2)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [35]:
np32=np.random.rand(10)
print(np.sort(np32))

[0.10219113 0.11389939 0.12222699 0.19603426 0.38992517 0.55844685
 0.61854709 0.89942576 0.92152634 0.93601134]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [38]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
np.array_equal(A,B)

[1 1 0 1 0]
[1 0 1 1 1]


False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [48]:
def func34(a):
    res=np.zeros((10,2))
    for i in range(10):
        res[i][0]=np.sqrt(a[i][0]**2+a[i][1]**2)
        res[i][1]=np.arctan2(a[i][0],a[i][1])
    return res
func34([[10,20],[-10,20],[-10,-20],[10,-20],[30,40],[-30,40],[-30,-40],[30,-40],[12,5],[12,-5]])

array([[22.36067977,  0.46364761],
       [22.36067977, -0.46364761],
       [22.36067977, -2.67794504],
       [22.36067977,  2.67794504],
       [50.        ,  0.64350111],
       [50.        , -0.64350111],
       [50.        , -2.49809154],
       [50.        ,  2.49809154],
       [13.        ,  1.17600521],
       [13.        ,  1.96558745]])

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [84]:
np32=np.random.randint(0,100,(10))
print(np32)
np32[np32.argmax()]=0
print(np32)

[13 45 74 77 76 50 91  2  8 77]
[13 45 74 77 76 50  0  2  8 77]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [67]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
emp=np.array([])
for i in range(100):
    emp=np.append(emp,abs(Z[i]-v))
    
print(Z[emp.argmin()])

47.69955215688366
48


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [70]:
Z = np.arange(9).reshape(3,3)
for index,x in np.ndenumerate(Z):
    print(index,x)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [77]:
Z = np.arange(9).reshape(3,3)
for index in np.ndindex(Z.shape):
    print(index,Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [82]:
Z = np.zeros((10,10))
np.put(Z, np.random.choice(range(10*10), 20, replace = False),5)
print(Z)

[[0. 0. 0. 0. 0. 0. 5. 0. 0. 0.]
 [5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 5. 0. 0. 5. 0. 5.]
 [5. 5. 0. 0. 0. 0. 0. 0. 5. 5.]
 [0. 5. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 5. 0. 0.]
 [5. 0. 0. 5. 5. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0. 0. 5.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [87]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[9 7 9]
 [3 1 9]
 [6 4 8]]


In [93]:
# column 1
Z=Z[Z[:,0].argsort()]
print(Z)

[[3 1 9]
 [6 4 8]
 [9 7 9]]


In [94]:
# column 2
Z=Z[Z[:,1].argsort()]
print(Z)

[[3 1 9]
 [6 4 8]
 [9 7 9]]


In [95]:
# column 3
Z=Z[Z[:,2].argsort()]
print(Z)

[[6 4 8]
 [3 1 9]
 [9 7 9]]
